# Generated by Django 5.0.1 on 2024-02-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/images'),
        ),
    ]
